#!/bin/sh
mkdir -p kernel/usr/initramfs
rm -rf kernel/usr/initramfs/*
cp -R ../initramfs_sgh-i777/* kernel/usr/initramfs
rm $(find kernel/usr/initramfs -name EMPTY_DIRECTORY -print)
rm -rf $(find kernel/usr/initramfs -name .git -print)
make c1_rev02_usa_att_defconfig
make -j16 && cp -a $(find . -name *.ko -print |grep -v initramfs) kernel/usr/initramfs/lib/modules/ && make -j16
# adb shell reboot download
# sleep 5
# heimdall flash --kernel arch/arm/boot/zImage
