# drivers/media/video/samsung/fimg2d/Makefile
#
# Copyright (c) 2010 Samsung Electronics Co., Ltd.
#	http://www.samsung.com/
#
# Licensed under GPLv2

obj-y				:=
obj-m				:=
obj-n				:=
obj-				:=

obj-$(CONFIG_VIDEO_FIMG2D) += fimg2d_drv.o fimg2d_ctx.o
obj-$(CONFIG_CPU_S5PV210) += fimg2d3x_blt.o fimg2d3x_hw.o
obj-$(CONFIG_CPU_S5PV310) += fimg2d3x_blt.o fimg2d3x_hw.o
