#
# Makefile for the kernel multimedia device drivers.
#

obj-y += common/ IR/ video/

obj-$(CONFIG_VIDEO_DEV) += radio/
obj-$(CONFIG_DVB_CORE)  += dvb/
obj-$(CONFIG_TDMB)  += tdmb/
obj-$(CONFIG_ISDBT_FC8100)	+= isdbt/
