#include <linux/gpio.h>
#include <linux/serial_core.h>
#include <plat/devs.h>
#include <plat/gpio-cfg.h>
#include <plat/regs-serial.h>
#include <mach/gpio.h>

struct gpio_init_data {
	uint num;
	uint cfg;
	uint val;
	uint pud;
	uint drv;
};

static struct gpio_init_data c1_init_gpios[] = {
#if defined(CONFIG_TDMB)
	{
	/* TDMB_INT */
		.num	= S5PV310_GPB(4),
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
	/* TDMB_RST_N */
		.num	= S5PV310_GPB(5),
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
	/* TDMB_EN*/
		.num	= S5PV310_GPC0(1),
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#elif defined(CONFIG_ISDBT_FC8100)
	{
	/* ISDBT_RST_N */
		.num	= S5PV310_GPE1(5),
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
	/* ISDBT_EN*/
		.num	= S5PV310_GPC0(1),
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#else
#if defined(CONFIG_TARGET_LOCALE_NA)
	{
		.num	= S5PV310_GPB(1),
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV4,
	},
#else
	{
		.num	= S5PV310_GPB(1),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#endif /* CONFIG_TARGET_LOCALE_NA */
	 {
		.num	= S5PV310_GPB(5),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#endif
	{
		.num	= S5PV310_GPB(6),
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV2,
	}, {
		.num	= S5PV310_GPB(7),
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV2,
	}, {
		.num	= S5PV310_GPC1(3),	/* CODEC_SDA_1.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPC1(4),	/* CODEC_SCL_1.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPD0(2),	/* MSENSOR_MHL_SDA_2.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPD0(3),	/* MSENSOR_MHL_SCL_2.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPD1(0),	/* 8M_CAM_SDA_2.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPD1(1),	/* 8M_CAM_SCL_2.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPD1(2),	/* SENSE_SDA_2.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPD1(3),	/* SENSE_SCL_2.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#if defined(CONFIG_TARGET_LOCALE_NA)
	{
		.num	= S5PV310_GPE1(6),	/*wimax EEP_SEL*/
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= S3C_GPIO_SETPIN_ONE,
		.pud	= S3C_GPIO_PULL_UP,
		.drv	= S5P_GPIO_DRVSTR_LV4,
	}, {
		.num	= S5PV310_GPE2(2),	/* VT_CAM_1.5V_EN*/
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV4,
	}, {
		.num    = S5PV310_GPJ0(0),  /* GPIO_CAM_PCLK*/
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num    = S5PV310_GPJ0(1),  /* GPIO_CAM_VSYNC*/
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPJ0(2),	/* GPIO_CAM_HSYNC */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPJ0(3),	/* GPIO_CAM_D0 */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPJ0(4),	/* GPIO_CAM_D1 */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPJ0(5),	/* GPIO_CAM_D2 */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPJ0(6),	/* GPIO_CAM_D3 */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPJ0(7),	/* GPIO_CAM_D4 */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPJ1(0),	/* GPIO_CAM_D5 */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPJ1(1),	/* GPIO_CAM_D6 */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPJ1(2),	/* GPIO_CAM_D7 */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPJ1(3),	/* GPIO_CAM_MCLK */
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{
		.num	= S5PV310_GPK1(1),
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV2,
	}, {
		.num	= S5PV310_GPK2(2),	/* PS_ALS_SDA_2.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#if defined(CONFIG_TARGET_LOCALE_NA)
	{
		.num	= S5PV310_GPK3(2),	/* PS_ALS_SCL_2.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPL0(4),
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV4,
	}, {
		.num    = S5PV310_GPL0(6),	/* NC */
		.cfg    = S3C_GPIO_INPUT,
		.val    = S3C_GPIO_SETPIN_ZERO,
		.pud    = S3C_GPIO_PULL_DOWN,
		.drv    = S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPL1(0),
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV4,
	}, {
		.num	= S5PV310_GPL1(2),
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV4,
	}, {
		.num	= S5PV310_GPL2(4),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPL2(5),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPX0(1),	/* VOL_UP */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#else
	{
		.num	= S5PV310_GPK3(1),	/* WLAN_SDIO_CMD */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPK3(2),	/* PS_ALS_SCL_2.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPK3(3),	/* WLAN_SDIO_D(0) */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPK3(4),	/* WLAN_SDIO_D(1) */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPK3(5),	/* WLAN_SDIO_D(2) */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPK3(6),	/* WLAN_SDIO_D(3) */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPX0(1),	/* VOL_UP */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{
		.num	= S5PV310_GPX0(2),	/* VOL_DOWN */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPX0(3),	/* GPIO_BOOT_MODE */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		/* TODO: remove belows if max17042 would be ready */
		.num	= S5PV310_GPX2(3),	/* GPIO_FUEL_ALERT */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPX3(1),
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPX3(2),	/* GPIO_DET_35 */
		.cfg	= S3C_GPIO_SFN(GPIO_DET_35_AF),
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#if defined(CONFIG_TARGET_LOCALE_NA)
	{
		.num	= S5PV310_GPX3(3),	/* NC */
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#else
	{
		.num	= S5PV310_GPX3(3),
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{
		.num	= S5PV310_GPX3(4),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#if defined(CONFIG_TARGET_LOCALE_NA) || defined(CONFIG_TARGET_LOCALE_NAATT)
	{
		.num	= S5PV310_GPX3(5),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#endif /* CONFIG_TARGET_LOCALE_NA */
#if defined(CONFIG_TARGET_LOCALE_NTT)
	{	/*GPY0 */
		.num	= S5PV310_GPY0(0),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY0(1),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#endif
#if !defined(CONFIG_MACH_C1_NA_SPR_REV05) && !defined(CONFIG_MACH_C1_NA_SPR_EPIC2_REV00)
	{	/*GPY0 */
		.num	= S5PV310_GPY0(2),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#endif
#if defined(CONFIG_MACH_C1_NA_SPR_REV05) || defined(CONFIG_MACH_C1_NA_SPR_EPIC2_REV00)
	{	/*GPY0 */
		.num	= S5PV310_GPY0(2),
		.cfg	= S3C_GPIO_SFN(3),
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#endif
	{
		.num	= S5PV310_GPY0(3),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#if !defined(CONFIG_MACH_C1_NA_SPR_REV05) && !defined(CONFIG_MACH_C1_NA_SPR_EPIC2_REV00)
	{
		.num	= S5PV310_GPY0(4),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY0(5),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#endif
#if defined(CONFIG_TARGET_LOCALE_NA)
	{	/*GPY1 */
		.num	= S5PV310_GPY1(0),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY1(1),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#else
	{	/*GPY1 */
		.num	= S5PV310_GPY1(0),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY1(1),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{
		.num	= S5PV310_GPY1(2),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#if !defined(CONFIG_MACH_C1_NA_SPR_REV05) && !defined(CONFIG_MACH_C1_NA_SPR_EPIC2_REV00)
	{
		.num	= S5PV310_GPY1(3),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},{	/*GPY2 */
		.num	= S5PV310_GPY2(0),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY2(1),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY2(2),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#endif
#if defined(CONFIG_MACH_C1_NA_SPR_REV05) || defined(CONFIG_MACH_C1_NA_SPR_EPIC2_REV00)
	{
		.num	= S5PV310_GPY1(3),
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},{	/*GPY2 */
		.num	= S5PV310_GPY2(0),
		.cfg	= S3C_GPIO_SFN(2),
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY2(1),
		.cfg	= S3C_GPIO_SFN(2),
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY2(2),
		.cfg	= S3C_GPIO_SFN(2),
		.val	= S3C_GPIO_SETPIN_NONE,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#endif
	{
		.num	= S5PV310_GPY2(3),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY2(4),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY2(5),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {	/*GPY4 */
		.num	= S5PV310_GPY4(4),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#if !defined(CONFIG_MACH_C1_NA_SPR_REV05) && !defined(CONFIG_MACH_C1_NA_SPR_EPIC2_REV00)
	{	/*GPY5 */
		.num	= S5PV310_GPY5(0),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY5(1),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY5(2),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY5(3),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY5(4),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY5(5),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY5(6),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY5(7),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#endif
	{	/* GPY6 */
		.num	= S5PV310_GPY6(0),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY6(1),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY6(2),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY6(3),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY6(4),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY6(5),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY6(6),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= S5PV310_GPY6(7),
		.cfg	= S3C_GPIO_INPUT,
		.val	= S3C_GPIO_SETPIN_ZERO,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
#if defined(CONFIG_TARGET_LOCALE_NA)
	{ /* WIMAX_EN */
		.num	= S5PV310_GPE1(7),
		.cfg	= S3C_GPIO_OUTPUT,
		.val    = S3C_GPIO_SETPIN_ZERO,
		.pud    = S3C_GPIO_PULL_NONE,
		.drv    = S5P_GPIO_DRVSTR_LV4,
	}, { /* WLAN_WAKE */
		.num	= S5PV310_GPD0(0),
		.cfg	= S3C_GPIO_INPUT,
		.val    = S3C_GPIO_SETPIN_ZERO,
		.pud    = S3C_GPIO_PULL_DOWN,
		.drv    = S5P_GPIO_DRVSTR_LV1,
	}, { /* WIMAX_SDIO_CLK */
		.num	= S5PV310_GPK3(0),
		.cfg	= S3C_GPIO_INPUT,
		.val    = S3C_GPIO_SETPIN_ZERO,
		.pud    = S3C_GPIO_PULL_DOWN,
		.drv    = S5P_GPIO_DRVSTR_LV1,
	}, { /* WIMAX_SDIO_CMD */
		.num	= S5PV310_GPK3(1),
		.cfg	= S3C_GPIO_INPUT,
		.val    = S3C_GPIO_SETPIN_ZERO,
		.pud    = S3C_GPIO_PULL_DOWN,
		.drv    = S5P_GPIO_DRVSTR_LV1,
	}, { /* WIMAX_SDIO_D(0) */
		.num	= S5PV310_GPK3(3),
		.cfg	= S3C_GPIO_INPUT,
		.val    = S3C_GPIO_SETPIN_ZERO,
		.pud    = S3C_GPIO_PULL_DOWN,
		.drv    = S5P_GPIO_DRVSTR_LV1,
	}, { /* WIMAX_SDIO_D(1) */
		.num	= S5PV310_GPK3(4),
		.cfg	= S3C_GPIO_INPUT,
		.val    = S3C_GPIO_SETPIN_ZERO,
		.pud    = S3C_GPIO_PULL_DOWN,
		.drv    = S5P_GPIO_DRVSTR_LV1,
	}, { /* WIMAX_SDIO_D(2) */
		.num	= S5PV310_GPK3(5),
		.cfg	= S3C_GPIO_INPUT,
		.val    = S3C_GPIO_SETPIN_ZERO,
		.pud    = S3C_GPIO_PULL_DOWN,
		.drv    = S5P_GPIO_DRVSTR_LV1,
	}, { /* WIMAX_SDIO_D(3) */
		.num	= S5PV310_GPK3(6),
		.cfg	= S3C_GPIO_INPUT,
		.val    = S3C_GPIO_SETPIN_ZERO,
		.pud    = S3C_GPIO_PULL_DOWN,
		.drv    = S5P_GPIO_DRVSTR_LV1,
	}, { /* WIMAX_EEP_SCL_1.8V */
		.num	= S5PV310_GPY0(0),
		.cfg	= S3C_GPIO_INPUT,
		.val    = S3C_GPIO_SETPIN_ZERO,
		.pud    = S3C_GPIO_PULL_DOWN,
		.drv    = S5P_GPIO_DRVSTR_LV1,
	}, { /* WIMAX_EEP_SDA_1.8V */
		.num	= S5PV310_GPY0(1),
		.cfg	= S3C_GPIO_INPUT,
		.val    = S3C_GPIO_SETPIN_ZERO,
		.pud    = S3C_GPIO_PULL_DOWN,
		.drv    = S5P_GPIO_DRVSTR_LV1,
	}, { /* WIMAX_MODE1 */
		.num	= S5PV310_GPY3(6),
		.cfg	= S3C_GPIO_OUTPUT,
		.val    = S3C_GPIO_SETPIN_ZERO,
		.pud    = S3C_GPIO_PULL_NONE,
		.drv    = S5P_GPIO_DRVSTR_LV4,
	}, {  /* WIMAX_MODE0 */
		.num	= S5PV310_GPY3(5),
		.cfg	= S3C_GPIO_OUTPUT,
		.val    = S3C_GPIO_SETPIN_ZERO,
		.pud    = S3C_GPIO_PULL_NONE,
		.drv    = S5P_GPIO_DRVSTR_LV4,
	}, { /* WIMAX_CON1 */
		.num	= S5PV310_GPL2(7),
		.cfg	= S3C_GPIO_OUTPUT,
		.val    = S3C_GPIO_SETPIN_ZERO,
		.pud    = S3C_GPIO_PULL_NONE,
		.drv    = S5P_GPIO_DRVSTR_LV4,
	}, { /* WIMAX_CON0 */
		.num	= S5PV310_GPL2(6),
		.cfg	= S3C_GPIO_OUTPUT,
		.val    = S3C_GPIO_SETPIN_ZERO,
		.pud    = S3C_GPIO_PULL_NONE,
		.drv    = S5P_GPIO_DRVSTR_LV4,
	}, { /* WIMAX_WAKEUP */
		.num	= S5PV310_GPX1(3),
		.cfg	= S3C_GPIO_OUTPUT,
		.val    = S3C_GPIO_SETPIN_ZERO,
		.pud    = S3C_GPIO_PULL_NONE,
		.drv    = S5P_GPIO_DRVSTR_LV4,
	}, { /* WIMAX_CON2 */
		.num	= S5PV310_GPE2(3),
		.cfg	= S3C_GPIO_OUTPUT,
		.val    = S3C_GPIO_SETPIN_ZERO,
		.pud    = S3C_GPIO_PULL_NONE,
		.drv    = S5P_GPIO_DRVSTR_LV4,
	}, { /* WIMAX_INT */
		.num	= S5PV310_GPX1(1),
		.cfg	= S3C_GPIO_OUTPUT,
		.val    = S3C_GPIO_SETPIN_NONE,
		.pud    = S3C_GPIO_PULL_NONE,
		.drv    = S5P_GPIO_DRVSTR_LV4,
	}, { /* WIMAX_RESET_N */
		.num	= S5PV310_GPA0(5),
		.cfg	= S3C_GPIO_OUTPUT,
		.val    = S3C_GPIO_SETPIN_ZERO,
		.pud    = S3C_GPIO_PULL_NONE,
		.drv    = S5P_GPIO_DRVSTR_LV4,
	}, { /*WIMAX_DBGEN_2.8V */
		.num	= S5PV310_GPA0(4),
		.cfg	= S3C_GPIO_OUTPUT,
		.val    = S3C_GPIO_SETPIN_ZERO,
		.pud    = S3C_GPIO_PULL_NONE,
		.drv    = S5P_GPIO_DRVSTR_LV4,
	},
#endif /* CONFIG_TARGET_LOCALE_NA */
};

void c1_config_gpio_table(void)
{
	u32 i, gpio;

	printk(KERN_DEBUG "c1_config_gpio_table.\n");

	for (i = 0; i < ARRAY_SIZE(c1_init_gpios); i++) {
		gpio = c1_init_gpios[i].num;
		if (gpio <= S5PV310_MP02(5)) {
			s3c_gpio_cfgpin(gpio, c1_init_gpios[i].cfg);
			s3c_gpio_setpull(gpio, c1_init_gpios[i].pud);

			if (c1_init_gpios[i].val != S3C_GPIO_SETPIN_NONE)
				gpio_set_value(gpio, c1_init_gpios[i].val);

			s5p_gpio_set_drvstr(gpio, c1_init_gpios[i].drv);
		}
	}
}

/* this table only for c1 board */
static unsigned int c1_sleep_gpio_table[][3] = {
#if defined(CONFIG_TARGET_LOCALE_NA)
	{ S5PV310_GPA0(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE}, /* BT_UART_RXD */
	{ S5PV310_GPA0(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE}, 
#else
	{ S5PV310_GPA0(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_UP},
	{ S5PV310_GPA0(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ S5PV310_GPA0(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
#if defined(CONFIG_TARGET_LOCALE_NA)
	{ S5PV310_GPA0(3),  S3C_GPIO_SLP_OUT1,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPA0(4),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* WIMAX_DBGEN_2.8V */
	{ S5PV310_GPA0(5),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* WIMAX_RESET_N */
#else
	{ S5PV310_GPA0(3),  S3C_GPIO_SLP_OUT1,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPA0(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPA0(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
#endif /* CONFIG_TARGET_LOCALE_NA */
#if defined(CONFIG_TARGET_LOCALE_NTT)
	{ S5PV310_GPA0(6),	S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE}, /* NC */
	{ S5PV310_GPA0(7),	S3C_GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE}, /* NC */
#else
#if defined(CONFIG_MACH_C1_NA_SPR_EPIC2_REV00)
	{ S5PV310_GPA0(6),	S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE}, /* KEY_EXPANDER_SDA */
	{ S5PV310_GPA0(7),	S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE}, /* KEY_EXPANDER_SCL */
#else
	{ S5PV310_GPA0(6),	S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN}, /* NC */
	{ S5PV310_GPA0(7),	S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN}, /* NC */
#endif
#endif
#if defined(CONFIG_TARGET_LOCALE_NA)
	{ S5PV310_GPA1(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPA1(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPA1(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPA1(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPA1(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPA1(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#else
	{ S5PV310_GPA1(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPA1(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPA1(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPA1(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPA1(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPA1(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
#if !defined(CONFIG_TDMB)
#if defined(CONFIG_TARGET_LOCALE_NTT)
	{ S5PV310_GPB(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPB(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPB(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPB(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPB(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPB(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#else
#if defined(CONFIG_TARGET_LOCALE_NAATT)
	{ S5PV310_GPB(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPB(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPB(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPB(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPB(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPB(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#else
	{ S5PV310_GPB(0),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
#if defined(CONFIG_TARGET_LOCALE_NA)
	{ S5PV310_GPB(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#else
	{ S5PV310_GPB(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ S5PV310_GPB(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPB(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ S5PV310_GPB(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif /* CONFIG_TARGET_LOCALE_NA */
#if defined(CONFIG_MACH_C1_NA_SPR_EPIC2_REV00)
	{ S5PV310_GPB(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#else
	{ S5PV310_GPB(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif
#endif
#endif
#else /* esper,2011-01-24 for KOR TDMB */
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ S5PV310_GPB(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPB(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPB(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPB(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPB(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPB(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
#endif
	{ S5PV310_GPB(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPB(7),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
#if defined(CONFIG_TARGET_LOCALE_NA)
	{ S5PV310_GPC0(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN}, /* REC_PCM_CLK */
#else
	{ S5PV310_GPC0(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
#if defined(CONFIG_TDMB) /* esper,2011-01-24 for KOR TDMB */
	{ S5PV310_GPC0(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#elif defined(CONFIG_ISDBT_FC8100)
	{ S5PV310_GPC0(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#else
#if  !defined(CONFIG_MACH_C1_NA_SPR_REV05) && !defined(CONFIG_MACH_C1_NA_SPR_EPIC2_REV00)
	{ S5PV310_GPC0(1), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
#endif
#endif
#if defined(CONFIG_TARGET_LOCALE_NA)
	{ S5PV310_GPC0(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN}, /* REC_PCM_SYNC */
#if  !defined(CONFIG_MACH_C1_NA_SPR_REV05) && !defined(CONFIG_MACH_C1_NA_SPR_EPIC2_REV00)
	{ S5PV310_GPC0(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN}, /* REC_PCM_IN */
#endif
	{ S5PV310_GPC0(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN}, /* REC_PCM_OUT */
#else
	{ S5PV310_GPC0(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPC0(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPC0(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */

	{ S5PV310_GPC1(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPC1(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPC1(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPC1(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPC1(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},

	{ S5PV310_GPD0(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPD0(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},	/* NC */
	{ S5PV310_GPD0(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPD0(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},

	{ S5PV310_GPD1(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPD1(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPD1(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPD1(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},

#if !defined(CONFIG_VIDEO_TSI)
#if defined(CONFIG_TARGET_LOCALE_NA)
	{ S5PV310_GPE0(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},  /* EBI2_WE_N */
	{ S5PV310_GPE0(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},  /* CP_DPRAM_CS_N */
	{ S5PV310_GPE0(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},  /* EBI2_OE_N */
	{ S5PV310_GPE0(3),  S3C_GPIO_SLP_OUT1,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE0(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},  /* NAND_ADV_N */
#else
	{ S5PV310_GPE0(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPE0(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE0(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPE0(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},

#endif /* CONFIG_TARGET_LOCALE_NA */
#endif
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ S5PV310_GPE0(4),  S3C_GPIO_SLP_OUT1,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */

	{ S5PV310_GPE1(0),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE1(1),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE1(2),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE1(3),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE1(4),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
#if !defined(CONFIG_VIDEO_TSI)
	{ S5PV310_GPE1(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPE1(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPE1(7),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif

#if defined(CONFIG_TARGET_LOCALE_NA)
	{ S5PV310_GPE2(0),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
#else
	{ S5PV310_GPE2(0),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_DOWN},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ S5PV310_GPE2(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE2(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ S5PV310_GPE2(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ S5PV310_GPE2(4),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE2(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#if defined(CONFIG_TARGET_LOCALE_NA)
	{ S5PV310_GPE3(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(0) */
	{ S5PV310_GPE3(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(1) */
	{ S5PV310_GPE3(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(2) */
	{ S5PV310_GPE3(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(3) */
	{ S5PV310_GPE3(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(4) */
	{ S5PV310_GPE3(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(5) */
	{ S5PV310_GPE3(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(6) */
	{ S5PV310_GPE3(7),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(7) */

	{ S5PV310_GPE4(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(8) */
	{ S5PV310_GPE4(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(9) */
	{ S5PV310_GPE4(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(10) */
	{ S5PV310_GPE4(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(11) */
	{ S5PV310_GPE4(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(12) */
	{ S5PV310_GPE4(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(13) */
	{ S5PV310_GPE4(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(14) */
	{ S5PV310_GPE4(7),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(15) */

	{ S5PV310_GPF0(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF0(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF0(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF0(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF0(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF0(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF0(6),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF0(7),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},

	{ S5PV310_GPF1(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF1(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF1(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF1(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF1(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF1(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF1(6),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF1(7),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},

	{ S5PV310_GPF2(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF2(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF2(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF2(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF2(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF2(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF2(6),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF2(7),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},

	{ S5PV310_GPF3(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF3(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF3(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF3(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF3(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF3(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#else
	{ S5PV310_GPE3(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE3(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE3(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE3(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE3(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE3(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE3(6),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE3(7),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},

	{ S5PV310_GPE4(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE4(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE4(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE4(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE4(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE4(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE4(6),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPE4(7),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},

	{ S5PV310_GPF0(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF0(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF0(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF0(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF0(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF0(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF0(6),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF0(7),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},

	{ S5PV310_GPF1(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF1(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF1(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF1(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF1(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF1(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF1(6),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF1(7),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},

	{ S5PV310_GPF2(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF2(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF2(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF2(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF2(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF2(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF2(6),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF2(7),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},

	{ S5PV310_GPF3(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF3(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF3(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF3(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF3(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPF3(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ S5PV310_GPJ0(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPJ0(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPJ0(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPJ0(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPJ0(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPJ0(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPJ0(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPJ0(7),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */

	{ S5PV310_GPJ1(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPJ1(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPJ1(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPJ1(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPJ1(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPK0(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPK0(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPK0(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPK0(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPK0(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPK0(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPK0(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},

	{ S5PV310_GPK1(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPK1(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPK1(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPK1(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPK1(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPK1(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPK1(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},

	{ S5PV310_GPK2(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
#if defined(CONFIG_MACH_C1_NA_SPR_REV05) || defined(CONFIG_MACH_C1_NA_SPR_EPIC2_REV00)
	{ S5PV310_GPK2(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE}, /* WIFI_CLK */
	{ S5PV310_GPK2(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE}, /* WIFI_CMD */
	{ S5PV310_GPK2(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE}, /* WIFI_D0 */
	{ S5PV310_GPK2(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPK2(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPK2(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
#else
	{ S5PV310_GPK2(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPK2(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPK2(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPK2(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPK2(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPK2(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
#endif

#if defined(CONFIG_TARGET_LOCALE_NA)
	{ S5PV310_GPK3(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},  /* WIMAX_SDIO_CLK */
#else
	{ S5PV310_GPK3(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ S5PV310_GPK3(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPK3(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPK3(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPK3(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPK3(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPK3(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPL0(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPL0(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPL0(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPL0(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPL0(4),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
#if defined(CONFIG_TARGET_LOCALE_NA)
	{ S5PV310_GPL0(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPL0(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* USB_SEL */
	{ S5PV310_GPL0(7),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#else
	{ S5PV310_GPL0(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPL0(6),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPL0(7),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */

	{ S5PV310_GPL1(0),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPL1(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPL1(2),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},

	{ S5PV310_GPL2(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPL2(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#ifdef	CONFIG_MAX8922_CHARGER
	{ S5PV310_GPL2(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#else
	{ S5PV310_GPL2(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif
	{ S5PV310_GPL2(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#ifdef	CONFIG_MAX8922_CHARGER
	{ S5PV310_GPL2(4),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPL2(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
#else
	{ S5PV310_GPL2(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPL2(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif
#if defined(CONFIG_TARGET_LOCALE_NTT)
	{ S5PV310_GPL2(6),	S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPL2(7),	S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
#else
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ S5PV310_GPL2(6),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPL2(7),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
#endif
#if defined(CONFIG_PN544) && defined(CONFIG_TARGET_LOCALE_KOR)
	{ S5PV310_GPL2(6),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPL2(7),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
#endif

#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ S5PV310_GPY0(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPY0(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
#endif /* CONFIG_TARGET_LOCALE_NA */
#if  !defined(CONFIG_MACH_C1_NA_SPR_REV05) && !defined(CONFIG_MACH_C1_NA_SPR_EPIC2_REV00)
	{ S5PV310_GPY0(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif
	{ S5PV310_GPY0(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#if  !defined(CONFIG_MACH_C1_NA_SPR_REV05) && !defined(CONFIG_MACH_C1_NA_SPR_EPIC2_REV00)
	{ S5PV310_GPY0(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPY0(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif
#if defined(CONFIG_TARGET_LOCALE_NA)
	{ S5PV310_GPY1(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPY1(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
#else
	{ S5PV310_GPY1(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPY1(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ S5PV310_GPY1(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#if  !defined(CONFIG_MACH_C1_NA_SPR_REV05) && !defined(CONFIG_MACH_C1_NA_SPR_EPIC2_REV00)
	{ S5PV310_GPY1(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif
#if  !defined(CONFIG_MACH_C1_NA_SPR_REV05) && !defined(CONFIG_MACH_C1_NA_SPR_EPIC2_REV00)
	{ S5PV310_GPY2(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPY2(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPY2(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif
	{ S5PV310_GPY2(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPY2(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#if  !defined(CONFIG_MACH_C1_NA_SPR_REV05) && !defined(CONFIG_MACH_C1_NA_SPR_EPIC2_REV00)
	{ S5PV310_GPY2(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif
#if defined(CONFIG_TARGET_LOCALE_NA)
	/* In Rev06, these pins are connected to always On LDOs */
	/* Assumes no effect in Rev03 and Rev05 boards */
	{ S5PV310_GPY3(0),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},
	{ S5PV310_GPY3(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPY3(2),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},
	{ S5PV310_GPY3(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#else
	{ S5PV310_GPY3(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},	/* MHL_SDA_1.8V */
	{ S5PV310_GPY3(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPY3(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},	/* MHL_SCL_1.8V */
	{ S5PV310_GPY3(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ S5PV310_GPY3(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ S5PV310_GPY3(5),  S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},
	{ S5PV310_GPY3(6),  S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ S5PV310_GPY3(7),  S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},

	{ S5PV310_GPY4(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPY4(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	/* GPIO_PDA_ACTIVE */
	{ S5PV310_GPY4(2),  S3C_GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE},
	{ S5PV310_GPY4(3),  S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},
#if  !defined(CONFIG_MACH_C1_NA_SPR_REV05) && !defined(CONFIG_MACH_C1_NA_SPR_EPIC2_REV00)
	{ S5PV310_GPY4(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif
	{ S5PV310_GPY4(5),  S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},
	/* GPIO_CP_REQ_RESET */
	{ S5PV310_GPY4(6),  S3C_GPIO_SLP_OUT1,	S3C_GPIO_PULL_NONE},
	/* GPIO_UART_SEL */
	{ S5PV310_GPY4(7),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},

#if !defined(CONFIG_MACH_C1_NA_SPR_REV05) && !defined(CONFIG_MACH_C1_NA_SPR_EPIC2_REV00)
	{ S5PV310_GPY5(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPY5(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPY5(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPY5(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPY5(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPY5(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPY5(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ S5PV310_GPY5(7),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
#endif
	{ S5PV310_GPY6(0),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPY6(1),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPY6(2),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPY6(3),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPY6(4),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPY6(5),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPY6(6),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPY6(7),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPZ(0),  S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},
	{ S5PV310_GPZ(1),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPZ(2),  S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},
	{ S5PV310_GPZ(3),  S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},
	{ S5PV310_GPZ(4),  S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},
	{ S5PV310_GPZ(5),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
	{ S5PV310_GPZ(6),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
#if defined(CONFIG_TARGET_LOCALE_NA)
	/*Wimax sleep gpio config start*/
	{ S5PV310_GPB(4),       S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE}, /* WIMAX_USB_EN */
	{ GPIO_WIMAX_DBGEN_28V, S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},
	{ GPIO_WIMAX_I2C_CON,	S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},
	{ GPIO_WIMAX_INT,	S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},
	{ GPIO_WIMAX_WAKEUP,	S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},
	{ GPIO_WIMAX_IF_MODE1,	S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},
	{ GPIO_WIMAX_IF_MODE0,	S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},
	{ GPIO_WIMAX_CON0,	S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},
	{ GPIO_WIMAX_CON1,	S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},
	{ GPIO_WIMAX_CON2,	S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},
	{ GPIO_WIMAX_EN	,	S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},
	{ GPIO_WIMAX_RESET_N,	S3C_GPIO_SLP_PREV,  S3C_GPIO_PULL_NONE},
	{ GPIO_CMC_SCL_18V,	S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},
	{ GPIO_CMC_SDA_18V,	S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},
	/*Wimax sleep gpio config end*/
#endif /* CONFIG_TARGET_LOCALE_NA */

#if defined(CONFIG_MACH_C1_NA_SPR_REV05) || defined(CONFIG_MACH_C1_NA_SPR_EPIC2_REV00)
	{ S5PV310_GPY2(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE}, /* SIDE_CLK_EN */
	{ S5PV310_GPC0(3),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_INT */
	{ S5PV310_GPY1(3),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_RST */
	{ S5PV310_GPY4(4),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_WAKEUP */
	{ S5PV310_GPY0(2),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_CS */
	{ S5PV310_GPY2(0),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_CLE */
	{ S5PV310_GPY2(1),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_ALE */
	{ S5PV310_GPY0(5),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_WE */
	{ S5PV310_GPY0(4),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_RE */
	{ S5PV310_GPY2(2),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_RB */
	{ S5PV310_GPY5(0),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_D0 */
	{ S5PV310_GPY5(1),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_D1 */
	{ S5PV310_GPY5(2),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPY5(3),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPY5(4),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPY5(5),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPY5(6),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ S5PV310_GPY5(7),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_D7 */
	{ S5PV310_GPC0(1),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* AP_T_FLASH_DETECT */
#endif

};

extern int s3c_gpio_slp_cfgpin(unsigned int pin, unsigned int config);
extern int s3c_gpio_slp_setpull_updown(unsigned int pin, unsigned int config);


static void config_sleep_gpio_table(int array_size, unsigned int (*gpio_table)[3])
{
	u32 i, gpio;

	for (i = 0; i < array_size; i++) {
		gpio = gpio_table[i][0];
		s3c_gpio_slp_cfgpin(gpio, gpio_table[i][1]);
		s3c_gpio_slp_setpull_updown(gpio, gpio_table[i][2]);
	}

#if defined(CONFIG_TARGET_LOCALE_NAATT)
	gpio_request(S5PV310_GPX2(4), "GPX24");
	gpio_direction_input(S5PV310_GPX2(4));
	s3c_gpio_setpull(S5PV310_GPX2(4), S3C_GPIO_PULL_DOWN);

	gpio_request(S5PV310_GPX3(0), "GPX30");
	gpio_direction_input(S5PV310_GPX3(0));
	s3c_gpio_setpull(S5PV310_GPX3(0), S3C_GPIO_PULL_DOWN);

	gpio_request(S5PV310_GPX3(5), "GPX35");
	gpio_direction_input(S5PV310_GPX3(5));
	s3c_gpio_setpull(S5PV310_GPX3(5), S3C_GPIO_PULL_DOWN);
#endif
#if defined(CONFIG_TARGET_LOCALE_NA) 
	gpio_direction_input(S5PV310_GPX1(5));
	s3c_gpio_setpull(S5PV310_GPX1(5), S3C_GPIO_PULL_DOWN);
#endif
#if defined(CONFIG_TARGET_LOCALE_NA)
	gpio_direction_output(S5PV310_GPX1(7), 0);
	s3c_gpio_setpull(S5PV310_GPX1(7), S3C_GPIO_PULL_NONE);
#ifndef CONFIG_MACH_C1_NA_SPR_EPIC2_REV00
	gpio_direction_input(S5PV310_GPX2(4));
	s3c_gpio_setpull(S5PV310_GPX2(4), S3C_GPIO_PULL_DOWN);
#endif
	gpio_direction_input(S5PV310_GPX3(3));
	s3c_gpio_setpull(S5PV310_GPX3(3), S3C_GPIO_PULL_DOWN);
#ifndef CONFIG_MACH_C1_NA_SPR_EPIC2_REV00
	gpio_direction_input(S5PV310_GPX3(5));
	s3c_gpio_setpull(S5PV310_GPX3(5), S3C_GPIO_PULL_DOWN);
#endif
	if (!gpio_get_value(GPIO_WIMAX_EN)) {
		for (i = 0; i <= 6; i++) {
			if (i != 2) {
				s3c_gpio_slp_cfgpin(S5PV310_GPK3(i), S3C_GPIO_SLP_INPUT);
				s3c_gpio_slp_setpull_updown(S5PV310_GPK3(i), S3C_GPIO_PULL_DOWN);
			}
		}
	}
#endif /* CONFIG_TARGET_LOCALE_NA */
}

void c1_config_sleep_gpio_table(void)
{
/*
	[Fix Me] Below codes are sample GPIO initialization and review codes
	for target platform if needed.
*/
	config_sleep_gpio_table(ARRAY_SIZE(c1_sleep_gpio_table),
			c1_sleep_gpio_table);
}

void s3c_setup_uart_cfg_gpio(struct platform_device *pdev)
{
	struct s3c2410_uartcfg *cfg =
	    (struct s3c2410_uartcfg *)(pdev->dev.platform_data);

	switch (cfg->hwport) {
	case 0:
		s3c_gpio_cfgpin(GPIO_BT_RXD, S3C_GPIO_SFN(GPIO_BT_RXD_AF));
		s3c_gpio_setpull(GPIO_BT_RXD, S3C_GPIO_PULL_NONE);
		s3c_gpio_cfgpin(GPIO_BT_TXD, S3C_GPIO_SFN(GPIO_BT_TXD_AF));
		s3c_gpio_setpull(GPIO_BT_TXD, S3C_GPIO_PULL_NONE);
		s3c_gpio_cfgpin(GPIO_BT_CTS, S3C_GPIO_SFN(GPIO_BT_CTS_AF));
		s3c_gpio_setpull(GPIO_BT_CTS, S3C_GPIO_PULL_NONE);
		s3c_gpio_cfgpin(GPIO_BT_RTS, S3C_GPIO_SFN(GPIO_BT_RTS_AF));
		s3c_gpio_setpull(GPIO_BT_RTS, S3C_GPIO_PULL_NONE);
		break;
#if !defined(CONFIG_TARGET_LOCALE_NA)
	case 1:
		s3c_gpio_cfgpin(GPIO_GPS_RXD, S3C_GPIO_SFN(GPIO_GPS_RXD_AF));
		s3c_gpio_setpull(GPIO_GPS_RXD, S3C_GPIO_PULL_UP);
		s3c_gpio_cfgpin(GPIO_GPS_TXD, S3C_GPIO_SFN(GPIO_GPS_TXD_AF));
		s3c_gpio_setpull(GPIO_GPS_TXD, S3C_GPIO_PULL_NONE);
#if defined(CONFIG_MACH_C1_REV00)
		s3c_gpio_cfgpin(GPIO_GPS_CTS, S3C_GPIO_SFN(GPIO_GPS_CTS_AF));
		s3c_gpio_setpull(GPIO_GPS_CTS, S3C_GPIO_PULL_NONE);
		s3c_gpio_cfgpin(GPIO_GPS_RTS, S3C_GPIO_SFN(GPIO_GPS_RTS_AF));
		s3c_gpio_setpull(GPIO_GPS_RTS, S3C_GPIO_PULL_NONE);
#endif
		break;

	case 3:
		s3c_gpio_cfgpin(GPIO_FLM_RXD, S3C_GPIO_SFN(GPIO_FLM_RXD_AF));
		s3c_gpio_setpull(GPIO_FLM_RXD, S3C_GPIO_PULL_UP);
#ifndef CONFIG_TARGET_LOCALE_NA
		s3c_gpio_cfgpin(GPIO_FLM_TXD, S3C_GPIO_SFN(GPIO_FLM_TXD_AF));
		s3c_gpio_setpull(GPIO_FLM_TXD, S3C_GPIO_PULL_NONE);
#endif /* CONFIG_TARGET_LOCALE_NA */
		break;
#endif

	default:
		break;
	}
}
