#################################################
# Makefile for Image Rotator 
# 2009 (C) Samsung Electronics 
# Author : Jonghun Han <jonghun.han@samsung.com>
#################################################

obj-$(CONFIG_CPU_S5PV210)	+= rotator_v2xx.o
obj-$(CONFIG_CPU_S5P6442)	+= rotator_v2xx.o

EXTRA_CFLAGS += -Idrivers/media/video

